---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      2D8E6431EB595D5B16D4A5D1F662E19726956441
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      826999DBE9E5B4C2A31FCB964E904DCBDD0DC384,
      2D8E6431EB595D5B16D4A5D1F662E19726956441
