---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age19vmwk33l6w8z72jj8ul0u3yqe4esxy7wlndq65sa02ynk060pf2qf537ew
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age19vmwk33l6w8z72jj8ul0u3yqe4esxy7wlndq65sa02ynk060pf2qf537ew
