# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:kG0JCl+AEyb6QJsxswnzp5XlT6uoJpgNDCkl2UXVu4EMFU86LA==,iv:nuPz074vPbvNGzOgHOFoxUdYuIe7c6BpL4vZYUGxSzY=,tag:OE7itWTAvYg3NFkmtEroog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19vmwk33l6w8z72jj8ul0u3yqe4esxy7wlndq65sa02ynk060pf2qf537ew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3V6WVNGVmdCcU14eSt5
            eU9PTnFzS2daTm94S1IraUJ6dHN4b2w3eEhRCm1zbVR3YW9Tb0l1UEZSSENlQkM2
            aU92RTFmallpMlQ2QzRjbzJWL1hjZW8KLS0tIHpvc2d4bXozZnpBeHNBcXh5UlV4
            aG11TzNGNUtReTRCVTNqNEhXRE1XaU0KtjngJOXL0XOBNBcl5LVgKw46xFQQWKuX
            kSB1Bw28WgARO/5TmS1zY3NhCII5jjnhy/A7OvCJ6Lenb2AtszX/Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-10T22:28:48Z"
    mac: ENC[AES256_GCM,data:mMVCaM1gaGVePoAuLHVTXwgE92S6VuUGzx6oNy/PZFsQNsjDpItqLvEHUEVWv06fdsSKF0Zt6dkGcPdE5bnpa2ZDe+t5zqDBt1zrA69A8VAuycFAHIO6sxDBGS58vfeyUhpkLd5H5C6T9nrtxLnPRrXvULlt3T/4SFzc+KBXF8A=,iv:/je9Yh4rfw4mzOqfrPdXFP89ok6OVU9VWTgX0PlkpYA=,tag:j5mgxXv9zB8J1D9xvlxlCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
